spring.application.name=cartify

spring.datasource.url=jdbc:postgresql://localhost:5432/CartifyDB
spring.datasource.username=postgres
spring.datasource.password=root

# Optional Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080